#!/bin/bash
#SBATCH -A csd453
#SBATCH --job-name="readsnap_6n2tpn"
#SBATCH --output="readsnap_6n2tpn.out"
#SBATCH --partition=compute
#SBATCH --nodes=6
#SBATCH --ntasks-per-node=2
#SBATCH --export=ALL
#SBATCH -t 02:00:00

pwd
source ./activate.sh
ibrun ./readsnap



