#!/bin/bash
#SBATCH -A csd453
#SBATCH --job-name="readsnap_4n4tpn"
#SBATCH --output="readsnap_4n4tpn.out"
#SBATCH --partition=compute
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=4
#SBATCH --export=ALL
#SBATCH -t 01:30:00

pwd
source ./activate.sh
ibrun ./readsnap



