#!/bin/bash
#SBATCH -A csd453
#SBATCH --job-name="readsnap_1n4tpn"
#SBATCH --output="readsnap_1n4tpn.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --export=ALL
#SBATCH -t 02:00:00

pwd
source ./activate.sh
ibrun ./readsnap



